name: Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  JAVA_VERSION: '21'

jobs:
  code-quality:
    name: KtLint & Detekt
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run KtLint
        id: ktlint
        run: ./gradlew ktlintCheck --no-daemon
        continue-on-error: true

      - name: Run Detekt
        id: detekt
        run: ./gradlew detekt --no-daemon
        continue-on-error: true

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-reports
          path: |
            build/reports/ktlint/
            build/reports/detekt/
          retention-days: 7

      - name: Check code quality results
        if: always()
        run: |
          if [[ "${{ steps.ktlint.outcome }}" == "failure" || "${{ steps.detekt.outcome }}" == "failure" ]]; then
            echo "Code quality checks failed!"
            echo "KtLint result: ${{ steps.ktlint.outcome }}"
            echo "Detekt result: ${{ steps.detekt.outcome }}"
            exit 1
          else
            echo "All code quality checks passed!"
          fi